asyncapi: 2.6.0
id: urn:com.github.pakisan.podlodkajavacrew4.rabbit-mock
info:
  title: Springwolf example project - AMQP
  version: 2.0.0
  description: Springwolf example project to demonstrate springwolfs abilities
defaultContentType: application/json
channels:
  another-queue:
    subscribe:
      bindings:
        amqp:
          expiration: 0
          cc:
            - another-queue
          bindingVersion: 0.3.0
      message:
        $ref: "#/components/messages/com.github.pakisan.podlodkajavacrew4.dtos.AnotherPayloadDto"
      examples:
        - example:
            someEnum: "{{randomValue(FOO1, FOO2, FOO3)}}"
            someLong: "{{randomInt(0, 100)}}"
            omeString: "{{randomString(64)}}"
          foo: "{{randomString(3)}}"
    bindings:
      amqp:
        is: queue
        queue:
          name: another-queue
          durable: false
          exclusive: false
          autoDelete: false
          vhost: /
        bindingVersion: 0.3.0
  example-producer-channel-publisher:
    publish:
      operationId: example-producer-channel-publisher_send
      description: Custom, optional description defined in the AsyncPublisher annotation
      bindings:
        amqp:
          expiration: 0
          cc: [ ]
          priority: 0
          deliveryMode: 1
          mandatory: false
          timestamp: false
          ack: false
          bindingVersion: 0.3.0
      message:
        $ref: "#/components/messages/com.github.pakisan.podlodkajavacrew4.dtos.AnotherPayloadDto"
      examples:
        - example:
            someEnum: "{{randomValue(FOO1, FOO2, FOO3)}}"
            someLong: "{{randomInt(0, 100)}}"
            omeString: "{{randomString(64)}}"
          foo: "{{randomString(3)}}"
  example-queue:
    subscribe:
      bindings:
        amqp:
          expiration: 0
          cc:
            - example-queue
          bindingVersion: 0.3.0
      message:
        $ref: "#/components/messages/com.github.pakisan.podlodkajavacrew4.dtos.ExamplePayloadDto"
      examples:
        - someEnum: "{{randomValue(FOO1, FOO2, FOO3)}}"
          someLong: "{{randomInt(0, 100)}}"
          someString: "{{randomString(64)}}"
    bindings:
      amqp:
        is: queue
        queue:
          name: example-queue
          durable: false
          exclusive: false
          autoDelete: false
          vhost: /
        bindingVersion: 0.3.0
  example-topic-routing-key:
    subscribe:
      bindings:
        amqp:
          expiration: 0
          cc:
            - example-topic-routing-key
          bindingVersion: 0.3.0
      message:
        $ref: "#/components/messages/com.github.pakisan.podlodkajavacrew4.dtos.AnotherPayloadDto"
      examples:
        - example:
            someEnum: "{{randomValue(FOO1, FOO2, FOO3)}}"
            someLong: "{{randomInt(0, 100)}}"
            omeString: "{{randomString(64)}}"
          foo: "{{randomString(3)}}"
    bindings:
      amqp:
        is: routingKey
        exchange:
          name: example-bindings-exchange-name
          type: topic
          durable: true
          autoDelete: false
          vhost: /
        bindingVersion: 0.3.0
  multi-payload-queue:
    subscribe:
      bindings:
        amqp:
          expiration: 0
          cc:
            - example-topic-routing-key
          bindingVersion: 0.3.0
      message:
        oneOf:
          - $ref: "#/components/messages/com.github.pakisan.podlodkajavacrew4.dtos.AnotherPayloadDto"
          - $ref: "#/components/messages/com.github.pakisan.podlodkajavacrew4.dtos.ExamplePayloadDto"
      examples:
        - example:
            someEnum: "{{randomValue(FOO1, FOO2, FOO3)}}"
            someLong: "{{randomInt(0, 100)}}"
            omeString: "{{randomString(64)}}"
          foo: "{{randomString(3)}}"
        - someEnum: "{{randomValue(FOO1, FOO2, FOO3)}}"
          someLong: "{{randomInt(0, 100)}}"
          someString: "{{randomString(64)}}"
    bindings:
      amqp:
        is: routingKey
        exchange:
          name: example-topic-exchange
          type: topic
          durable: true
          autoDelete: false
          vhost: /
        bindingVersion: 0.3.0
components:
  schemas:
    HeadersNotDocumented:
      type: object
      properties: {}
      examples:
        - {}
    com.github.pakisan.podlodkajavacrew4.dtos.AnotherPayloadDto:
      type: object
      properties:
        example:
          $ref: "#/components/schemas/com.github.pakisan.podlodkajavacrew4.dtos.ExamplePayloadDto"
        foo:
          type: string
          description: Foo field
          examples:
            - bar
      description: Another payload model
      examples:
        - example:
            someEnum: FOO2
            someLong: 5
            someString: some string value
          foo: bar
      required:
        - example
    com.github.pakisan.podlodkajavacrew4.dtos.ExamplePayloadDto:
      type: object
      properties:
        someEnum:
          type: string
          description: Some enum field
          enum:
            - FOO1
            - FOO2
            - FOO3
          examples:
            - FOO2
        someLong:
          type: integer
          description: Some long field
          format: int64
          examples:
            - 5
        someString:
          type: string
          description: Some string field
          examples:
            - some string value
      description: Example payload model
      examples:
        - someEnum: FOO2
          someLong: 5
          someString: some string value
      required:
        - someEnum
        - someString
  messages:
    com.github.pakisan.podlodkajavacrew4.dtos.AnotherPayloadDto:
      headers:
        $ref: "#/components/schemas/HeadersNotDocumented"
      payload:
        schemaFormat: application/vnd.aai.asyncapi+json;version=3.0.0
        schema:
          $ref: "#/components/schemas/com.github.pakisan.podlodkajavacrew4.dtos.AnotherPayloadDto"
      name: com.github.pakisan.podlodkajavacrew4.dtos.AnotherPayloadDto
      title: AnotherPayloadDto
      description: Another payload model
      bindings:
        amqp:
          bindingVersion: 0.3.0
    com.github.pakisan.podlodkajavacrew4.dtos.ExamplePayloadDto:
      headers:
        $ref: "#/components/schemas/HeadersNotDocumented"
      payload:
        schemaFormat: application/vnd.aai.asyncapi+json;version=3.0.0
        schema:
          $ref: "#/components/schemas/com.github.pakisan.podlodkajavacrew4.dtos.ExamplePayloadDto"
      name: com.github.pakisan.podlodkajavacrew4.dtos.ExamplePayloadDto
      title: ExamplePayloadDto
      bindings:
        amqp:
          bindingVersion: 0.3.0